name: gerrit-operator
operator:
  image:
    name: mdtu-ddm-edp-cicd/gerrit-operator
    version: 2.12.0-SNAPSHOT.1-1668595949
  serviceAccountName: gerrit-operator
  clusterRoleName: gerrit-operator-role-mdtu-ddm-edp-cicd

gerrit:
  name: gerrit
  image:
    name: openfrontier/gerrit
    version: 3.3.2
  storage:
    size: 5Gi
  sshPort: 30999
  port: 8080
  serviceAccountName: gerrit
  basePath: gerrit

keycloakIntegration:
  enabled: true
  client:
    name: gerrit
    public: false
    secretName: gerrit-is-credentials
  realm: admin

sentinel: {}

dockerRegistry: docker-registry.openshift-image-registry.svc
global:
  storageClass: ocs-storagecluster-ceph-rbd
  platform: openshift
  gerrit:
    administrators: []
    readers: []
keycloak:
  host: platform-keycloak:8080
image:
  version: 1.1.1-1
dnsWildcard: mdtu-ddm.edp.epam.com
edpProject: mdtu-ddm-edp-cicd
namespace: ns
cdPipelineName: pipe
cdPipelineStageName: dev
