apiVersion: v2.edp.epam.com/v1
kind: Gerrit
metadata:
  name: gerrit
  labels:
  {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
spec:
  keycloakSpec:
    enabled: {{ .Values.keycloakIntegration.enabled }}
    realm: {{ template "keycloak.realm" . }}
    url: {{ template "admin-tools.gerritUrl" . }}
  sshPort: {{ .Values.gerrit.sshPort }}
  basePath: {{ .Values.gerrit.basePath }}
