apiVersion: batch/v1
kind: Job
metadata:
  name: gerrit-configure-all-projects-repo
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.gerrit.name }}
    {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: gerrit-configure-all-projects-repo
    spec:
      initContainers:
        - name: gerrit-ready-443
          image: {{ template "imageRegistry" . -}} curlimages/curl
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - '-c'
            - while ! nc -w 1 {{ template "gerrit.hostname" . }} 443 </dev/null; do echo waiting for gerrit ready; sleep 10; done;
      containers:
        - name: gerrit-configure-all-projects-repo-init
          image: {{ template "imageRegistry" . -}} bitnami/git
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "/tmp/scripts/configure_all_project_repo.sh"]
          volumeMounts:
            - name: script-configure-all-projects-repo
              mountPath: /tmp/scripts/configure_all_project_repo.sh
              subPath: configure_all_project_repo.sh
          env:
            - name: GERRIT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gerrit-admin-password
                  key: user
            - name: GERRIT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gerrit-admin-password
                  key: password
      volumes:
        - name: script-configure-all-projects-repo
          configMap:
            name: script-configure-all-projects-repo
            defaultMode: 0755
      restartPolicy: Never
      serviceAccountName: {{ .Values.gerrit.serviceAccountName }}