kind: ConfigMap
apiVersion: v1
metadata:
  name: gerrit-jenkins-plugin-config-url-patch
  labels:
  {{- include "gerrit-operator.metaLabels" . | nindent 4 }}

data:
  context: |
    import com.sonyericsson.hudson.plugins.gerrit.trigger.GerritServer
    import com.sonyericsson.hudson.plugins.gerrit.trigger.PluginImpl
    import com.sonyericsson.hudson.plugins.gerrit.trigger.config.PluginConfig
    import net.sf.json.*

    PluginImpl plugin = PluginImpl.getInstance();
    PluginConfig pluginConfig = plugin.getPluginConfig();

    for (gerritServer in plugin.getServers()) {
        if (gerritServer.name == "gerrit") {
       		gerritServer.getConfig().setGerritFrontEndURL({{ include "admin-tools.gerritUrl" . }})
            println(gerritServer.name + " GerritServer Frontend URL is patched to " + gerritServer.getConfig().getGerritFrontEndUrl())
        }
    }
