apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    {{ template "admin-routes.whitelist.annotation" . }}
  labels:
    app: gerrit
    {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
  name: gerrit
spec:
  host: {{ template "admin-tools.hostname" . }}
  path: /{{ .Values.gerrit.basePath }}
  port:
    targetPort: {{ .Values.gerrit.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gerrit
    weight: 100
  wildcardPolicy: None
