{{- if .Values.keycloakIntegration.enabled -}}
{{- if not .Values.keycloakIntegration.client.public -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakIntegration.client.secretName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
  {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ template "gerrit.keycloak-secret" . }}
{{- end -}}
{{- end -}}
