apiVersion: v1
kind: Service
metadata:
  name: admin-tools-gerrit
  annotations:
    ingress.kubernetes.io/service-upstream: 'true'
    konghq.com/override: kong-admin-tools-set-timeouts
    konghq.com/path: /
    konghq.com/plugins: gerrit-nopublic-oidc
    konghq.com/protocol: http
  labels:
    app: gerrit
    {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
spec:
  ports:
    - name: ui
      protocol: TCP
      port: {{ .Values.gerrit.port }}
      targetPort: {{ .Values.gerrit.port }}
  selector:
    app: gerrit
